# Generated by Django 5.0.4 on 2024-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='avatar_url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='github_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
