# Generated by Django 5.0.4 on 2024-04-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_githubuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='public_repos_links',
            field=models.TextField(blank=True, default=''),
        ),
    ]
