# Generated by Django 5.0.4 on 2024-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_githubrepositories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepositories',
            name='repo_user',
            field=models.CharField(max_length=255),
        ),
    ]
