# Generated by Django 5.0.4 on 2024-04-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjumper_app', '0003_githubuser_public_repos_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repo_link', models.CharField(default='', max_length=255, unique=True)),
                ('repo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjumper_app.githubuser')),
            ],
        ),
    ]
