# Generated by Django 5.0.4 on 2024-04-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjumper_app', '0005_alter_githubrepositories_repo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='public_repos_links',
        ),
    ]
